// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmlxalqllwzgiadbtnug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptbHhhbHFsbHd6Z2lhZGJ0bnVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTgyNDUsImV4cCI6MjA2NDQ3NDI0NX0.PRm96kXlCxayDVaBOC3PjNmfUNSWxTIip7sQnCx-VYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);